[tools]
task = '3.42.1'
go = '1.24.1'
goreleaser = '2.8.1'
act = '0.2.75'
'golangci-lint' = '1.64.7'
'ubi:dominikh/go-tools' = { version = '2025.1.1', exe = 'staticcheck', tar_regex = '^staticcheck_\.' }
'ubi:psampaz/go-mod-outdated' = '0.9.0'
#'go:golang.org/x/pkgsite/cmd/pkgsite' = 'latest'
'ubi:KeepSec-Technologies/Mail2Go' = { version = '1.1.8', exe = 'mail2go', tar_regex = '^mail2go_\.' }
